### ISSUE TITLE
Not simple enough

### ISSUE THREAD

**Issue by Jcd1230** [Remeil/Simple-Game#1]
The game is simple, but is it really embracing the simplicity it was designed to simple?

**Comment by Remeil** [comment]
Simply, it falls down to the simple fact that the game is simple. Sometimes the simplicity of simple game doesn't seem simple, but in fact, it is so simple that it could be conceived as not simple.

Closed as not simply reproducible.

**Comment by Jcd1230** [comment]
I would simply like to thank you for the simple explanation.
